version: "3.4"

services:

  samba:
    image: dperson/samba
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 137:137/udp
      - 138:138/udp     
      - 139:130/tcp
      - 445:445/tcp
    volumes:
      - /usr/share/zoneinfo/America/Chile/Santiago:/etc/localtime
      - /home/Compartido/carpeta1:/carpeta1
      - /home/Compartido/carpeta2:/carpeta2 
      - /home/Compartido/carpeta3:/carpeta3  
    command: '-s "carpeta1;/carpeta1;yes;no;no" -u "admin;p@ssword" -p'
    command: '-s "carpeta2;/carpeta2;yes;no;no" -u "admin;admin2021*" -p'
    command: '-s "carpeta3;/carpeta3;yes;no;no" -u "admin;admin2020*" -p'
