version: "3.4"

services:

  samba:
    image: dperson/samba
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Chile/Santiago:/etc/localtime
      - /home/Compartido/carpeta1:/carpeta1
      - /home/Compartido/carpeta2:/carpeta2 
      - /home/Compartido/carpeta3:/carpeta3  
    command: '-s "carpeta1;/carpeta1;yes;no;no;admin1" -u "admin1;p@ssword" -s "carpeta2;/carpeta2;yes;no;no;admin2" -u "admin2;admin2021*" -s "carpeta3;/carpeta3;yes;no;no;admin3" -u "admin3;admin2020*"'
